### PR TITLE
fix for nextUrl

### PR DESCRIPTION
**Pull request by EnergoStalin**
fix for nextUrl now it looks like this
image

### CODE REVIEW

**Comment by EnergoStalin** [comment]
nice tests

**Comment by everpcpc** [comment]
Could you provide some example results to `fixtures`?

**Comment by EnergoStalin** [comment]
did not inspect such inconsistency should be fixed now considering both max_bookmark_id and offset legitemate next id's

**Comment by everpcpc** [comment]
thanks!

**Pull request merged**
